#!/bin/bash
# Create a dated text file at a specific location and append text to it.
#
# Usage:
#   $ notes something you want to jot down (appends that text to the file)
#   $ xclip -o | notes                     (appends your clipboard to the file)
#   $ notes                                (opens the file in your editor)
#
# Produces:
#   YYYY-MM.txt in your $NOTES_DIRECTORY (this is set below).

set -e

readonly NOTES_DIRECTORY="${NOTES_DIRECTORY:-"${HOME}/notes"}"
readonly NOTES_EDITOR="vim"
#readonly NOTES_EDITOR="${EDITOR}"

readonly NOTES_FILE="$(date +%Y-%m-%d).txt"
readonly NOTES_FILEPATH="${NOTES_DIRECTORY}/$(date +%Y)/$(date +%B)/${NOTES_FILE}"
readonly NOTES_PATH="${NOTES_DIRECTORY}/$(date +%Y)/$(date +%B)"

# check if file is not existing
if [ ! -d "${NOTES_PATH}" ]; then
	mkdir -p "${NOTES_PATH}"
fi

if [ ! -f "${NOTES_FILEPATH}" ]; then
	touch "${NOTES_FILEPATH}"
	echo "Notes from : $(date +%Y-%m-%d)" >> "${NOTES_FILEPATH}"
	echo "-----------------------" >> "${NOTES_FILEPATH}"
	echo "" >> "${NOTES_FILEPATH}"
fi

# check if folder notes is not existing
if [ ! -d "${NOTES_DIRECTORY}" ]; then
	while true; do
		read -rp "${NOTES_DIRECTORY} does not exist, do you want to create it? (y/n) " yn
		case "${yn}" in
			[Yy]* ) mkdir -p "${NOTES_DIRECTORY}"; break;;
			[Nn]* ) exit;;
			* ) echo "Please answer y or n";;
		esac
	done
fi

if [ ${#} -eq 0 ]; then
	if [ -p "/dev/stdin" ]; then
		(cat; printf "\n\n") >> "${NOTES_FILEPATH}"
	else
		eval "${NOTES_EDITOR}" "${NOTES_FILEPATH}"
	fi
else
	printf "%s\n\n" "${*}" >> "${NOTES_FILEPATH}"
fi
